### ISSUE TITLE
Can't build with OpenSSL 1.1.0 or later

### ISSUE THREAD

**Issue by kenhys** [pyama86/mruby-acme-client#4]
## Problem

mruby-acme-client can't build with OpenSSL 1.1.0 or later.

## Actual

1. clone mruby 

```
% git clone https://github.com/mruby/mruby.git
```

2. clone mruby-acme-client

```
% git clone https://github.com/pyama86/mruby-acme-client.git mruby-acme-client.work
```

3. fix gem path to mruby-acme-client

```
% vim mruby/build_config.rb
% cd mruby && git diff
diff --git a/build_config.rb b/build_config.rb
index 1429837b..a15dfd32 100644
--- a/build_config.rb
+++ b/build_config.rb
@@ -20,6 +20,7 @@ MRuby::Build.new do |conf|
   # conf.gem :mgem => 'mruby-io'
   # conf.gem :github => 'iij/mruby-io'
   # conf.gem :git => 'git@github.com:iij/mruby-io.git', :branch => 'master', :options => '-v'
+  conf.gem '../mruby-acme-client.work'

   # include the default GEMs
   conf.gembox 'default'

```

4. make

```
% cd mruby && make
```

5. some build error occurs.

```
--
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c:72:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   EVP_PKEY *pkey;
   ^~~~~~~~
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c: In function 'ossl_rsa_new':
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c:154:27: error: dereferencing pointer to incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
     if (EVP_PKEY_type(pkey->type) != EVP_PKEY_RSA) {
                           ^~
In file included from /home/kenhys/work/ruby/mruby/include/mruby/value.h:148:0,
                 from /home/kenhys/work/ruby/mruby/include/mruby.h:87,
--
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c:72:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   EVP_PKEY *pkey;
   ^~~~~~~~
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c: In function 'ossl_rsa_new':
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c:154:27: error: dereferencing pointer to incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
     if (EVP_PKEY_type(pkey->type) != EVP_PKEY_RSA) {
                           ^~
In file included from /home/kenhys/work/ruby/mruby/include/mruby/value.h:148:0,
                 from /home/kenhys/work/ruby/mruby/include/mruby.h:87,
--
/home/kenhys/work/ruby/mruby-acme-client.work/src/ossl_pkey_rsa.c:190:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
rake aborted!
```

I've noticed this problem on Debian unstable.

```
 dpkg -l G ssl-dev
ii  libssl-dev:amd64                      1.1.0g-2                              amd64        Secure Sockets Layer toolkit - development files
```

Here is the actual build log file.

[build.log](https://github.com/pyama86/mruby-acme-client/files/1570309/build.log)

## Expected

make succeeds with OpenSSL 1.1.0 or later.

**Comment by pyama86** [comment]
Thank you for reporting.
I am aware of the problem, but I have not planned to respond because it is not practical.

**Comment by pyama86** [comment]
![image](https://user-images.githubusercontent.com/8022082/34143876-467f72e0-e4d2-11e7-9c18-ce4a0d8aa8c4.png)
https://twitter.com/pyama86/status/943004915235827712
tonokotodesu.
